# Site settings
title: InSpace
url: "https://inspaceai.github.io"
baseurl: ""
motto: Intelligence in Space
email: hansoli@inspace.re.kr
description: Intelligence in Space

# Build settings
markdown: kramdown

# post future
future: true

# pagination
paginate: 10
