# Site settings
url: "https://inspaceai.github.io"
baseurl: ""
brief-intro: Intelligence in Space
email: hansoli@inspace.re.kr
description: InSpace Artificial Intelligence Lab
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# post future
future: true

# comment
disqus: inspaceai

# pagination
category_dir: category/
tag_dir: tag/
gems: [jekyll-paginate]
paginate: 10
